In [46]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import utils
import glob
import re
import pandas as pd

In [13]:
def string_to_number(st):
    stt = re.sub('^-','',st)
    if re.match('^\d+$', stt):
        return int(st)
    elif re.match('[\d\.]+',stt):
        return float(st)
    return st
assert(string_to_number('123123') == 123123)
assert(string_to_number('-123123') == -123123)
assert(string_to_number('0.2123123') == 0.2123123)
assert(string_to_number('-0.21123') == -0.21123)

In [14]:
def extract_output(log_dir):

    config = utils.loadConfig()
    path = config['BASE_LOG_DIR'] + '/' + log_dir + '/*'

    files = glob.glob(path)
    no_files = len(files)
    print('Found %d files in %s' % (no_files, path))

    results = []
    for fp in files:
        with open(fp) as f:
            columns = dict()
            lines = f.readlines()
            hyper_block = False
            for line in lines:
                reg_ex = '^-+'
                if re.match(reg_ex, line):
                    hyper_block = not hyper_block
                    
                if hyper_block and not re.match(reg_ex, line):
                    k,v = re.split(" *: +", line.strip())
                    columns[k] = string_to_number(v)
    
            last_lines = lines[-2].replace("Last output: ","")
            
            for t in last_lines.split('|'):
                k,v = re.split(" *: +", t.strip())
                columns[k] = string_to_number(v)
            results.append(columns)
    return pd.DataFrame(results)

In [47]:
show_columns = ['RNN Scope','Number of hidden Units','Loss','TestLoss','TestMin', 'TrainMin']

In [60]:
extract_output("2d")[show_columns].sort_values('TestMin')

Found 28 files in ./log/2d/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
3,rnn-cell-2d-1497731697,100,MIN,-0.924,-0.968,-0.993
2,rnn-cell-2d-1497731360,60,MIN,-0.955,-0.960,-0.980
0,rnn-cell-2d-1497730689,10,MIN,-0.947,-0.958,-0.932
1,rnn-cell-2d-1497731024,30,MIN,-0.944,-0.950,-0.960
26,rnn-cell-2d-1497781350,60,OI_UPDATED,-0.925,-0.933,-0.964
27,rnn-cell-2d-1497781757,100,OI_UPDATED,-0.923,-0.922,-0.937
19,rnn-cell-2d-1497737347,100,SUMMIN,-13.919,-0.917,-0.928
18,rnn-cell-2d-1497737004,60,SUMMIN,-13.537,-0.911,-0.921
7,rnn-cell-2d-1497733046,100,SUM,-12.771,-0.900,-0.899
11,rnn-cell-2d-1497734400,100,WSUM,-6.777,-0.900,-0.902
22,rnn-cell-2d-1497738360,60,WSUM_EXPO,-0.595,-0.898,-0.896
10,rnn-cell-2d-1497734059,60,WSUM,-6.873,-0.894,-0.900
25,rnn-cell-2d-1497780941,30,OI_UPDATED,-0.889,-0.885,-0.874
23,rnn-cell-2d-1497738698,100,WSUM_EXPO,-0.593,-0.883,-0.873
17,rnn-cell-2d-1497736663,30,SUMMIN,-13.067,-0.880,-0.864
9,rnn-cell-2d-1497733722,30,WSUM,-6.416,-0.879,-0.856
21,rnn-cell-2d-1497738027,30,WSUM_EXPO,-0.581,-0.873,-0.863
24,rnn-cell-2d-1497780517,10,OI_UPDATED,-0.864,-0.861,-0.833
5,rnn-cell-2d-1497732367,30,SUM,-12.020,-0.855,-0.843
6,rnn-cell-2d-1497732707,60,SUM,-12.217,-0.853,-0.860
20,rnn-cell-2d-1497737690,10,WSUM_EXPO,-0.487,-0.778,-0.745
16,rnn-cell-2d-1497736321,10,SUMMIN,-10.393,-0.703,-0.660
4,rnn-cell-2d-1497732032,10,SUM,-8.262,-0.565,-0.532
8,rnn-cell-2d-1497733384,10,WSUM,-4.332,-0.560,-0.529
15,rnn-cell-2d-1497735924,100,OI,4.817,-0.416,-0.369
14,rnn-cell-2d-1497735527,60,OI,7.516,-0.351,-0.318
13,rnn-cell-2d-1497735129,30,OI,8.291,-0.263,-0.232
12,rnn-cell-2d-1497734734,10,OI,0.199,-0.258,-0.224

# 3d Models

In [49]:
extract_output("3d-rbf")[show_columns].sort_values('TestMin')[:10]

Found 8 files in ./log/3d-rbf/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
0,rnn-cell-3d-1498175944,60,MIN,-0.839,-0.848,-0.969
1,rnn-cell-3d-1498176338,100,MIN,-0.840,-0.848,-0.972
6,rnn-cell-3d-1498178416,60,WSUM_EXPO,-0.524,-0.839,-0.908
5,rnn-cell-3d-1498178016,100,SUMMIN,-11.741,-0.801,-0.915
4,rnn-cell-3d-1498177616,60,SUMMIN,-11.727,-0.788,-0.891
7,rnn-cell-3d-1498178812,100,WSUM_EXPO,-0.454,-0.776,-0.901
2,rnn-cell-3d-1498176732,60,OI,-0.734,-0.752,-0.825
3,rnn-cell-3d-1498177173,100,OI,-0.595,-0.610,-0.641

In [50]:
extract_output("3d-matern32")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/3d-matern32/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
5,rnn-cell-3d-1498181506,100,SUMMIN,-11.930,-0.880,-0.938
0,rnn-cell-3d-1498179215,60,MIN,-0.874,-0.877,-0.923
7,rnn-cell-3d-1498182372,100,WSUM_EXPO,-0.527,-0.863,-0.899
1,rnn-cell-3d-1498179654,100,MIN,-0.799,-0.801,-0.900
4,rnn-cell-3d-1498181075,60,SUMMIN,-10.171,-0.753,-0.841

In [51]:
extract_output("3d-matern52")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/3d-matern52/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
1,rnn-cell-3d-1498183322,100,MIN,-0.857,-0.858,-0.910
0,rnn-cell-3d-1498182808,60,MIN,-0.782,-0.784,-0.893
7,rnn-cell-3d-1498186525,100,WSUM_EXPO,-0.452,-0.724,-0.836
4,rnn-cell-3d-1498184965,60,SUMMIN,-9.244,-0.696,-0.801
6,rnn-cell-3d-1498186009,60,WSUM_EXPO,-0.399,-0.675,-0.739

# 4d Models

In [52]:
extract_output("4d-rbf")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/4d-rbf/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
1,rnn-cell-4d-1498250543,100,MIN,-0.777,-0.801,-1.048
0,rnn-cell-4d-1498250146,60,MIN,-0.789,-0.798,-0.952
5,rnn-cell-4d-1498252230,100,SUMMIN,-10.194,-0.747,-0.965
7,rnn-cell-4d-1498253030,100,WSUM_EXPO,-0.396,-0.745,-0.937
4,rnn-cell-4d-1498251827,60,SUMMIN,-10.139,-0.744,-0.887

In [53]:
extract_output("4d-matern32")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/4d-matern32/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
3,rnn-cell-4d-1498254809,100,OI,-0.884,-0.903,-0.995
1,rnn-cell-4d-1498253875,100,MIN,-0.845,-0.853,-1.115
2,rnn-cell-4d-1498254315,60,OI,-0.734,-0.741,-0.893
7,rnn-cell-4d-1498256652,100,WSUM_EXPO,-0.344,-0.707,-1.046
4,rnn-cell-4d-1498255305,60,SUMMIN,-8.064,-0.673,-0.894

In [54]:
extract_output("4d-matern52")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/4d-matern52/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
1,rnn-cell-4d-1498257618,100,MIN,-0.827,-0.835,-1.053
7,rnn-cell-4d-1498260745,100,WSUM_EXPO,-0.459,-0.829,-1.020
3,rnn-cell-4d-1498258692,100,OI,-0.723,-0.738,-0.878
5,rnn-cell-4d-1498259742,100,SUMMIN,-8.802,-0.725,-1.030
6,rnn-cell-4d-1498260243,60,WSUM_EXPO,-0.357,-0.682,-0.892

# 6d Models

In [55]:
extract_output("6d-rbf")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/6d-rbf/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
1,rnn-cell-6d-1498291713,100,MIN,-0.929,-0.955,-1.273
0,rnn-cell-6d-1498291320,60,MIN,-0.796,-0.813,-1.071
5,rnn-cell-6d-1498293398,100,SUMMIN,-8.971,-0.733,-1.163
7,rnn-cell-6d-1498294196,100,WSUM_EXPO,-0.310,-0.709,-1.103
2,rnn-cell-6d-1498292110,60,OI,-0.671,-0.691,-0.869

In [56]:
extract_output("6d-matern32")[show_columns].sort_values('TestMin')[:5]

Found 8 files in ./log/6d-matern32/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
1,rnn-cell-6d-1498295036,100,MIN,-0.942,-0.957,-1.616
3,rnn-cell-6d-1498295967,100,OI,-0.548,-0.568,-1.070
5,rnn-cell-6d-1498296907,100,SUMMIN,-4.418,-0.493,-1.297
0,rnn-cell-6d-1498294597,60,MIN,-0.434,-0.442,-0.877
7,rnn-cell-6d-1498297782,100,WSUM_EXPO,-0.160,-0.411,-0.821

In [59]:
extract_output("6d-matern52")[show_columns].sort_values('TestMin')

Found 8 files in ./log/6d-matern52/*

,RNN Scope,Number of hidden Units,Loss,TestLoss,TestMin,TrainMin
7,rnn-cell-6d-1498301947,100,WSUM_EXPO,-0.211,-0.582,-1.317
1,rnn-cell-6d-1498298732,100,MIN,-0.508,-0.518,-1.166
5,rnn-cell-6d-1498300906,100,SUMMIN,-4.812,-0.512,-1.220
0,rnn-cell-6d-1498298215,60,MIN,-0.471,-0.479,-0.962
3,rnn-cell-6d-1498299817,100,OI,-0.442,-0.452,-0.996
4,rnn-cell-6d-1498300385,60,SUMMIN,-3.823,-0.419,-0.865
2,rnn-cell-6d-1498299249,60,OI,-0.411,-0.415,-0.748
6,rnn-cell-6d-1498301430,60,WSUM_EXPO,-0.152,-0.412,-0.814